name: Pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    strategy:
      matrix:
        task: ["build", "lint", "test"]
        os: [ubuntu-latest]
        go-version: [1.23.1]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-

      - name: Run task ${{ matrix.task }}
        run: make ${{ matrix.task }}
        env:
          GOPATH: /home/runner/go
